component: frontend
service_type: LoadBalancer
port: 80
container_port: 80
target_port: 80
PARAMETERS_ENABLED: false

resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 500m
    memory: 500Mi