component: frontend
service_type: LoadBalancer
port: 80
env: prod
PARAMETERS: "frontend.prod.appVersion,appVersion"
schema:
  enabled: false

replicaCount: 2

recordName: www.rdevops74.online
ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: www.rdevops74.online
      paths:
        - path: /
          pathType: ImplementationSpecific